# -*- coding: utf-8 -*-
"""Copy of No12Group_Cynthia_Fitri_IT4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Z4mB1DaXP6pPKd9NZPRZf0OsOuguEFmi
"""

# Cynthia
# Fitri
# IT 4
print("Pilih jenis Bensin (1.Premium, 2.Pertalite, 3.Pertamax, 4.Diesel) 0.Stop")
a = b = c = d = 0
while True:
  B = int(input())
  if B == 1:
    a = a+1
  elif B == 2:
    b = b+1
  elif B == 3:
    c = c+1
  elif B == 4:
    d = d+1
  elif B == 0:
    break
print("Output : ")
print("Premium: {}".format(a))
print("Pertalite: {}".format(b))
print("Pertamax: {}".format(c))
print("Diesel: {}".format(d))