# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zfZ7F-6CvELJhZm7qtgfz9TnPCpJRC2m
"""

#Variable
a = 10
b = 3.14 #(float)
c = "Fitri" #(String)
# f = True/False (huruf depan kapital(boolean)
g=[] #(list)
h={} #(dictionary)
i=() #(tuple)
# print("F")/ print('F')
# print (2) / print (2+3*10)
# print (c)--> fitri

#concate (gabungin string)
print("hai aku " + c)

print("hai aku {}".format(c))

#ubah angka ke string
print("nilai adalah" + str(a))

print("nilainya adalah {}".format(a))

#gabungin banyak string
print("namaku{}, nilaiku {}, dan isianku {}". format(c,a,b))

sekolah = ["kelas",10, True, 3.14, ["budi","bubu","bobo"], {"hewan":"gajah"}]

print(sekolah)

sekolah[0:5:2]

sekolah[4][2]

sekolah[0]

sekolah[4][0]

sekolah[4]

sekolah[-1]

nama_siswa = ["budi","bubu","bobo","cici","lala","kiki"]

nama_siswa[2:5]#2,3,4

nama_siswa[-2:]

Dict = {"hewan":"gajah", 0:22, "Boolean":"benar"}

Dict["hewan"]

Dict[0]

Dict["Boolean"]